const _publicKey = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1RBRSAZeFTkDh1hNUdCV
04urqRerRKDXG/ffAXbxG0plu0Gg0qWSrjtcf2fTMTirEUn6Pg82kp8lrEBfgIxC
619Tt+BzpCQVh4zpPFDcwKvAzJSssN2ZX93qVKCbU/cze47GIircCyViSAiUR76E
epEPMDPdiM/4X5oU/23I1axPLnfbJ0iVXXhG03bguuJSBA4VUIRXJ7c3crCSHheS
rraEjAvp4MaHgQWWQb/URkMOlhTxy/A0bW2CQgZQ89RxcH4n5cX1yn/C3+mqMEOJ
oEYCB+MpzHkY7F/N8JpJrn9vbucWjGZAdIr8kUKkAqsJ+XzQ+74/6GkU3W0bIcZk
owIDAQAB
-----END PUBLIC KEY-----`;
//HDFC Public Key
// const _publicKey = `-----BEGIN PUBLIC KEY-----
// MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2n/pc8IfNd7Gx9YuaIt6
// QZGlNTP4XNYpT9n+woZkDPnntrrZnaIY9NUnKsIEjoPX+tecnEwYmMmCswZiP6QQ
// XfgixcaIgRGnf9NOHz+EvBFgGNUE2rcAWG/uav5yrNMV5me7Jx/1Lo+N6Ewr2EtB
// wqnTbldpKCXYURl3thXNdXZ+iOMKeQQKUCHBRMhd3FPZiB5UqtPMB5S9YJZcuWpI
// tEa88P8qLCLnZvf+mf+4XcjrKu+HFYztOWLKZ+olmzVd60XKvLO0/V6BRvOSYbVz
// vdD+1d7lV679WbtoXWZnQm/okYVHarzzBdoMUgtszvP7r32y3tD/HBODbwvOjEBS
// 3wIDAQAB
// -----END PUBLIC KEY-----`;

module.exports = {
   _publicKey,
};
